### ISSUE TITLE
freshenRemoteObject fails because of 'multipart upload copy'

### ISSUE THREAD

**Issue by timprijn** [instaclustr/esop#52]
Each night Icarus/Esop backups our Cassandra data and we noticed the following errors in our logs:

- `ERROR com.instaclustr.esop.impl.backup.UploadTracker$UploadUnit - Failed to upload file ....`
- ` com.amazonaws.SdkClientException: Unable to copy part: null (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey;....`

A small number of files failed to backup. Despite these errors the backup process still finished in state `COMPLETED`. We used Icarus 1.0.1 and upgraded to 1.0.9, because we noticed some differences that seemed relevant. However, the same errors still occur, but now the backup finishes in state FAILED (which already is an improvement).

After an extensive analysis we noticed that files which are initially uploaded with 'multipart upload' succeed. When they are already present at our Ceph Object Gateway (S3) then the code does a https://github.com/instaclustr/esop/blob/20c7f1f58a92e6cf9a6d46dd46cfa88663dbaf43/src/main/java/com/instaclustr/esop/s3/BaseS3Backuper.java#L60 which runs https://github.com/instaclustr/esop/blob/20c7f1f58a92e6cf9a6d46dd46cfa88663dbaf43/src/main/java/com/instaclustr/esop/s3/BaseS3Backuper.java#L72 This unfortunately results in a https://github.com/instaclustr/esop/blob/20c7f1f58a92e6cf9a6d46dd46cfa88663dbaf43/src/main/java/com/instaclustr/esop/s3/BaseS3Backuper.java#L87 and the mentioned errors. Note that this exception only happens for files that are copied with 'multipart upload' (https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html).

We are able to reproduce the above 'multipart upload copy' behaviour to our S3 with a Minio client and it seems an issue with our S3. Currently we are looking into the problem with our S3 and hope that this will be resolved after a major upgrade. For now we created an Esop patch in which we set the configuration attribute `multipartCopyThreshold` to a large number to ensure the copy (in `freshenRemoteObject`) does not apply a multipart upload and the backup succeeds.

Despite the fact this issue is most probably related to our Ceph Object Gateway, I was wondering why the `freshenRemoteObject` does a copy? Is it to determine if the file is already uploaded? Does it do more than determining if the file is already uploaded? What does freshening mean? And can this be implemented perhaps by other calls and be less dependent on catching exceptions to determine the flow of code?

**Comment by smiklosovic** [comment]
Hi @timprijn 

thanks for reaching us. This is honestly an issue which repeats itself and I am not completely sure anymore which solution is the right one because there are multiple S3 providers (AWS, Oracle, IBM, Ceph ...) and everybody seems to be opinionated about this very piece of the functionality and it just does not work for all S3 implementations same way.

Refreshing means that it will change "the last modified date" of that object. That is good for your retention policy as you might decide that you do want to automatically remove objects which are older than e.g. 14 days. If a particular object is not refreshed during 14 days, it will be automatically removed. Now if you are doing backups repeatedly and the whole philosophy of Esop is to not ever upload same objects twice, it means that we do "refresh" of that object on its modification date but we will keep it there otherwise intact - if it is there. If it is not there, we upload.

This "if it is there" is done by `transferManager.copy(copyRequest)`, if you notice, we copy a file into itself (few lines above where that copy request is being constructed).

There is also "metadata directive" (1) which is by default COPY.  But it can be also REPLACE. Now this is where various S3 providers differ - one expects COPY, other expects REPLACE and you might kill me but I just do not know for now which needs which.

What you might do is to play with this setting - change COPY to REPLACE - and it might start to work as expected. It is driven by this flag (2)

Let me know how it goes!

(1) https://github.com/instaclustr/esop/blob/20c7f1f58a92e6cf9a6d46dd46cfa88663dbaf43/src/main/java/com/instaclustr/esop/s3/BaseS3Backuper.java#L65
(2) https://github.com/instaclustr/esop/blob/20c7f1f58a92e6cf9a6d46dd46cfa88663dbaf43/src/main/java/com/instaclustr/esop/impl/backup/BaseBackupOperationRequest.java#L52-L70

**Comment by smiklosovic** [comment]
Hey @timprijn 

After reading your message twice I see that

_For now we created an Esop patch in which we set the configuration attribute multipartCopyThreshold to a large number to ensure the copy (in freshenRemoteObject) does not apply a multipart upload and the backup succeeds._

This is good. I am glad you resolved it ... I so maybe my initial response is little bit off but you might give it a shot if it changes anything or not in your context anyway

**Comment by smiklosovic** [comment]
Hi @timprijn 

I just finished this https://github.com/instaclustr/esop/tree/skip-refreshing

Our customer was versioning files in s3 bucket and replacement and copy would still create new versioned file and it was occupying a lot of place.

So you have a possiblity to completely bypass that refreshing logic with implications mentioned in readme.

**Comment by timprijn** [comment]
Hi,

Sorry for the late response. We has some other prio's, holiday... and other lame excuses :)

I was looking into this branch and it seems perfect for us. In our case we don't have a retention policy and we do not apply versioning, so skipping this step seems perfect. I'll test this branch in our situation and let you know.

Just wondering: will this option be released to master and if so, do you know when? And can I do something to get this released?

**Comment by smiklosovic** [comment]
Hi @timprijn ,

no worries, if you confirm it works for you, I will gladly merge & release it.

**Comment by timprijn** [comment]
Hi @smiklosovic,

The "skip" branch works perfectly for us and it is a better solution than the workaround I introduced. Thnx in advance for merging and releasing!

**Comment by smiklosovic** [comment]
@timprijn 

released as https://github.com/instaclustr/esop/releases/tag/esop-1.1.2
