### ISSUE TITLE
[FEATURE] enablePathStyleAccess as a configurable option instead of directly coupled to the Module

### ISSUE THREAD

**Issue by timprijn** [instaclustr/esop#53]
**Is your feature request related to a problem? Please describe.**
Since we start using Esop for backup (1.0.1) we are using `oracle//` as the protocol in our `storagelocation` despite the fact we use Ceph Object Gateway S3. The primary reason we used `oracle` is because our Ceph implementation only supports `path style access`. After upgrading to 1.0.9 we noticed the existence of a CephModule which seems more logic to use. However, this CephModule always creates the TransferManagerFactory with 'disabled' path style access. 

**Describe the solution you'd like**
To be able to configure whether one would like to use path style access, possibly as an attribute on the request?

**Describe alternatives you've considered**
Keep on using the `oracle://` which at first seems weird and needs to be clarified in our docs.

**Comment by smiklosovic** [comment]
Hi @timprijn ,

this is a very simple change, all you need to do is to change this `false` to `true` (1). That boolean says if path style should be enabled or not. It is `true` for Oracle module but `false` for Ceph module.

I do not have any problem to change it to `true`, but I wonder ... I am not completely familiar with this, if it has to be _always_ true or if it should be somehow configurable.

If that needs to be configurable (once true, once false, as one pleases), I do not see _yet_ some convenient and simple way how to make it configurable, because of the other things unrelated to this feature, it is complicated to explain here.

So if we want that true / false to be flexible, a simple win would be to read some system property (like -Dceph.enablePathStyle=true|false).

Would that work for you? Is in your capacity to make this change (to true), build the stuff (./mvnw clean install -DskipTests) and test if it works?

https://github.com/instaclustr/esop/blob/20c7f1f58a92e6cf9a6d46dd46cfa88663dbaf43/src/main/java/com/instaclustr/esop/s3/ceph/CephModule.java#L38

**Comment by timprijn** [comment]
Goodmorning @smiklosovic,

Thnx for the quick reply! 

I'll look into the question if it should always be one of them or if it needs to be configurable and get back to you. Dependent on the outcome I will create the appropriate pull request with some additional info.

**Comment by smiklosovic** [comment]
Hi @timprijn ,

is this still an issue for you?

**Comment by timprijn** [comment]
Hi,

Last friday afternoon I started with this issue and the first step was to determine if it should be configurable or not. I concluded it's best to make it configurable. Currently different implementations of S3 already support virtual access, but some not. According to https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/ path style access wil no longer be supported in the long run. However, for now it is there and I believe that making it configurable helps in migrating. 

Your mentioned option for an additional environment variable makes sense and is in line with the current implementation of `S3Configuration` and resolveS3Configuration. I implemented this, patched it locally and configured Icarus to use this patched version. However during testing this setup I ran into some problems...

Currently there's no working latest version of Icarus with the latest from Esop (this build fails). I think I'll need to wait for that and then patch Esop with my changes, so I can test everything. 

If I'm mistaken in this analysis please let me know.

**Comment by smiklosovic** [comment]
Hi @timprijn 

I have released latest Icarus (1.1.1) with latest Esop (1.1.2).

Regards

**Comment by timprijn** [comment]
Hi,

Thnx for releasing! Based on these latest versions I made the described changes and tested successfully that I am now able to the Ceph module with path-style URL's as we need for our Ceph S3 configuration.

Hopefully the pull request will meet the requirements and, if not, I will gladly process some review comments. Unfortunately, it seems that running all the unit/integration tests at my machine fail regardless of my changes...

**Comment by smiklosovic** [comment]
what errors are you hitting? `mvn clean install` should be just enough.

**Comment by timprijn** [comment]
The tests failed (during clean install), after a closer look I noticed that some property for the JVM couldn't be applied and then I remembered I'm using Java 11 and the Embedded older version of Cassandra only works with 1.8. After switching I could successfully run a clean install.
