### ISSUE TITLE
Misleading "Couldn't generate checksum for" exception

### ISSUE THREAD

**Issue by timprijn** [instaclustr/esop#55]
_Exceptions during backup_
We started receiving exceptions during the backup process with stacktraces like:

```
java.io.UncheckedIOException: java.io.IOException: java.lang.IllegalStateException: Couldn't generate checksum for /icarus/cassandra/data/data/archive/something-b2d9cc3051c411eb8a29851d977a39d8/snapshots/autosnap-1621338376-73919840-436c-3d25-a9d8-42659f4e5722-1621338385981/md-347-big-Digest.crc32
	at com.instaclustr.esop.impl.SSTableUtils.lambda$ssTableManifest$2(SSTableUtils.java:124)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.instaclustr.esop.impl.Snapshots$Snapshot$Keyspace$Table.parse(Snapshots.java:519)
	at com.instaclustr.esop.impl.Snapshots$Snapshot$Keyspace.parse(Snapshots.java:354)
	at com.instaclustr.esop.impl.Snapshots$Snapshot.parse(Snapshots.java:221)
	at com.instaclustr.esop.impl.Snapshots.parse(Snapshots.java:679)
	at 
.....
```

We are using Cassandra 3.11 and this code flow should only be executed for 2.XX (https://github.com/instaclustr/esop/blob/06928e39ce143c9fa6b7c3fc865718d2007da8d6/src/main/java/com/instaclustr/esop/impl/SSTableUtils.java#L56). 

It took a lot of analysis and debugging understand that the root cause was that we accidentally ran multiple backups in parallel. When the first started backup cleans up its snapshots, the second backup was still working with data from the first backup. This is because of `Snapshots.parse` which resolves all files at a certain moment in time. In our case the second backup also found snapshot files from the first backup, which were later cleaned by the first backup.

We fixed the issue of "multiple running backups at the same time", but I was wondering if it is possible to detect if a backup is already running from each Sidecar and if it is, then stop the backup process with a log statement or so. 

_Cause for multiple running backups_
We have, for instance, three running Cassandra instances. Each of them have Icarus as a sidecar. The REST request for creating a backup is done at a load balancer, which directs to instance A. Then a script does a periodic request to determine the status of the backup job until it is done or failed. Our script didn't account for the fact that executing this request against another instance (B for example) results in a 404. Subsequently the script failed and was restarted. Then another backup request was done at instance B (or C). Apparently only instance A knows about this operation. We know changed our script to always execute the backup request to instance A and also ask for the status on instance A.

It seems that we didn't have these issues in the past or at least they weren't that explicit and consistent. I cannot determine precisely why we are experiencing this issue more than before. 

_Summary_

- Is the analysis correct that only the instance on which the backup is requested (coordinator) knows about the status?
- Is it simply possible to determine if a backup is already running, so it can be stopped directly and no unexpected follow-up errors like `Couldn't generete checksum..` occur.

**Comment by smiklosovic** [comment]
Hi @timprijn ,

I am not completely sure I am following your explanation. The thing is that Esop / Icarus is done in such a way that parallel backups are absolutely fine to do. This was done on purpose so a person A can issue a backup request and 5 minutes later person B can run another one and they will just execute in parallel, side by side. If there is some overlapping of entities to backup, this will be handled automatically and no sstable is ever backuped up more than once.

https://github.com/instaclustr/esop#simultaneous-backups

The workflow should be like this:

1) you have 3 node cluster
2) you issue one backup request which "global" (if you dont follow here, just say and I will expand on this)
3) coordinator will automatically disperse these requests to two other nodes (and to itself, so 3 requests are sent, one of them to same node, it is kind of a loop)
4) each node is doing backup and status is polled from coordinator
5) one each node is done, coordinator detects this and the whole "global request" is done

Now I am not completely sure why you would see such error but just by looking at it, the easy fix would be to synchronize the access to this logic which parses the snapshots so it would not clash as it is effectively executed from different threads. 

I did this in Esop (1) so what you can do is to build Esop on your own, bump that version in Icarus and build that one too and you might try it out.

I had to forcepush master in Esop  (yay!) because I forgot to bump it to next development iteration, you will see it from git log so please fetch the current master as is and try to build and let me know if it is better.

(1) https://github.com/instaclustr/esop/commit/87e3d0049af5534866995ec1f406dc856fd17c00

**Comment by smiklosovic** [comment]
Ok I see what you mean, I can see it in the code ... well ... yeah this seems to be a problem, I am not sure how to fix it yet, I need to give it a second thought, I will update this issue once I have something new.

**Comment by timprijn** [comment]
Goodmorning,

Just tested with Esop master and I'm still seeing the same errors when running multiple backups in parallel, including the "Couldn't generate checksum".

I think that at the time the check happens to return an empty stream, the snapshot files still exist (they aren't cleared yet). During processing of the stream, files are removed and then the errors happen.

Perhaps it's best to queue the backups or only clear snapshots when no other backups are running?

**Comment by smiklosovic** [comment]
@timprijn thanks for trying it in more depth. I do not want to queue them. They have to be trully done in parallel, that is the requirement of the other business we are delivering this for and us queuing it would violate what we promissed them to do.

**Comment by smiklosovic** [comment]
Hi @timprijn 

please use this Icarus with changes in Esop

https://oss.sonatype.org/content/repositories/snapshots/com/instaclustr/icarus/1.1.2-SNAPSHOT/

Thanks!
